# Generated by Django 5.0.4 on 2024-04-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquetcategory',
            name='image',
        ),
    ]
